cc_library(
    name = "serialize_interface",
    srcs = [
    ],
    hdrs = [
        "iserialize.hpp",
    ],
    strip_include_prefix = "",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "member_access_interface",
    srcs = [
    ],
    hdrs = [
        "imember_access.hpp",
    ],
    strip_include_prefix = "",
    visibility = ["//visibility:public"],
)
