cc_library(
    name = "serialize_interface",
    srcs = [
    ],
    hdrs = [
        "iserialize.hpp",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "member_access_interface",
    srcs = [
    ],
    hdrs = [
        "imember_access.hpp",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "validate_interface",
    srcs = [
    ],
    hdrs = [
        "ivalidate.hpp",
    ],
    visibility = ["//visibility:public"],
)
